using static NNUESettings;

using System.Reflection;


public static class NNUEWeights
{
    /// <summary>
    /// [king bucket][feature][node]
    /// </summary>
    public static short[][][] ftWeights;

    /// <summary>
    /// [feature]
    /// </summary>
    public static short[] ftBias;

    /// <summary>
    /// [material buket][output node][ft node]
    /// </summary>
    public static short[][][] OutputWeight;

    /// <summary>
    /// [maerial bucket][output node]
    /// </summary>
    public static short[][] OutputBias;


    static NNUEWeights() 
    {
        ftWeights = new short[IN_BUCKET_CNT][][];
        ftBias = new short[FT_SIZE];

        for (int buck=0; buck<IN_BUCKET_CNT; buck++)
        {
            ftWeights[buck] = new short[INPUT_SIZE][];

            for (int feat=0; feat<INPUT_SIZE; feat++)
                ftWeights[buck][feat] = new short[FT_SIZE];
        }

        OutputWeight = new short[OUT_BUCKET_CNT][][];
        OutputBias   = new short[OUT_BUCKET_CNT][];

        for (int buck=0; buck<OUT_BUCKET_CNT; buck++)
        {
            OutputBias[buck] = new short[OUTPUT_SIZE];
            OutputWeight[buck] = new short[OUTPUT_SIZE][];

            for (int node=0; node<OUTPUT_SIZE; node++)
                OutputWeight[buck][node] = new short[FT_SIZE * 2];
        }
    }

    /// <summary>
    /// loads the Weights into the already initialized Arrays. Reads from binary files generated by the
    /// bullet-trainer (https://github.com/jw1912/bullet). Thanks jw!
    /// </summary>
    public static void load() 
    {   

        // read the embedded file
        Stream? stream;
        if ((stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(
            $"Schneckbert.Evaluate.Nets.{net_name}.bin"
        )) == null)
        {
            throw new Exception($"Could not find embedded {net_name}");
        }

        using (var reader = new BinaryReader(stream))
        {

            // Feature Transformer weights
            for (int buck=0; buck<IN_BUCKET_CNT; buck++)
                for (int feat=0; feat<INPUT_SIZE; feat++)
                    for (int node=0; node<FT_SIZE; node++)
                        ftWeights[buck][feat][node] = reader.ReadInt16();

            // Feature Transformer bias
            for (int node=0; node<FT_SIZE; node++)
                ftBias[node] = reader.ReadInt16();

            // Output (hidden layer 1) weights
            if (net_name == "simple192_wdl50")
            {
                for (int buck=0; buck<OUT_BUCKET_CNT; buck++) 
                    for (int feat=0; feat<FT_SIZE*2; feat++)
                            OutputWeight[buck][0][feat] = reader.ReadInt16();
            }
            else
            {
                for (int node=0; node<OUTPUT_SIZE; node++)
                    for (int feat=0; feat<FT_SIZE*2; feat++)
                        for (int buck=0; buck<OUT_BUCKET_CNT; buck++)    
                            OutputWeight[buck][node][feat] = reader.ReadInt16();
            }

            // Output (hidden layer 1) bias
            for (int buck=0; buck<OUT_BUCKET_CNT; buck++)
                for (int node=0; node<OUTPUT_SIZE; node++)
                    OutputBias[buck][node] = reader.ReadInt16();

            /*
            // debug help: bullet files print "bullet" in the remaining buffer-bytes of the quantized file
            // bullet-files are bufferd to multiples of 64 bytes
            try
            {
                while (true) Console.WriteLine(reader.ReadChar());
            } catch {}
            */
            
        }
    }
}
